### ISSUE TITLE
Add styling to the website, make it look cool.

### ISSUE THREAD

**Issue by zetabug** [zetabug/react-weather-application#1]

**Comment by Halim-Shams** [comment]
I can work on this can you assign this to me?

**Comment by Halim-Shams** [comment]
I can work on this can you assign this to me?

**Comment by zetabug** [comment]
Okay sure, do share the screenshot in the PR. Make sure you've added your name in [https://github.com/zetabug/react-weather-application/blob/main/CONTRIBUTING.md](url) CONTRIBUTING.md file.

**Comment by singhimat99** [comment]
Hey I would love to work on this can you assign this to me?

**Comment by zetabug** [comment]
> Hey I would love to work on this can you assign this to me?

Ok, make it look good.

**Comment by AnthonyHad** [comment]
@singhimat99 Let's make this look good ! 
I am working on some optimisations for the search maybe some proper error handling as well and why not turn this whole thing into a bigger project to practice even more if everyone agrees ^^

**Comment by niranjana1997** [comment]
Is it alright if I work on this too?

**Comment by JPTomorrow** [comment]
I'll pitch in for a few PR's if you still have room to add me.

**Comment by consci210** [comment]
@zetabug  I can add styling to the page . The page looks plain now so I can add some hover effects, create dark mode and light mode toggle ,and also add links that direct to this Github repository  .

**Comment by Nyland-Sidifall** [comment]
I'd love to add to this project! Any objections to using TailwindCSS?

**Comment by HughesSeanKyle** [comment]
Would like to contribute to this project as well.

**Comment by axsiya** [comment]
@zetabug Hi,I'd like to know if this is the current status of the website and i could make some changes if you'd like to.Do let me know.

**Comment by Venu4054** [comment]
Hey I would love to work on this can you assign this to me?

**Comment by Deeshon** [comment]
Hey i would like to work on this.  Lets make the website look a lil more modern and interactive. Can you assign this to me?

**Comment by NIKHILNAIR21** [comment]
Hey I would love to work on this can you assign this to me @zetabug

**Comment by ashishk1331** [comment]
Can I also hop on the thread? I can design the app.
I can make minimal stuff.
![image](https://github.com/zetabug/react-weather-application/assets/44055846/d8530e88-b871-4031-99b1-f1e9467f4695)

**Comment by gasangw** [comment]
- Hello @zetabug is this issue open? Let me know if I can work on It
