### ISSUE TITLE
Remove CRA template from README as a Good First Issue

### ISSUE THREAD

**Issue by Medic1111** [zetabug/react-weather-application#13]
> Readme still has CRA Template

---

- [ ] Assist devs new to collaborations to tackle a simple yet needed task
- [ ] In addition, dev could specify to to run the app locally

---

**Comment by RDiMag** [comment]
Hi @Medic1111 Can I claim this issue?

**Comment by Medic1111** [comment]
> Hi @Medic1111 Can I claim this issue?

Hey! I wish I could say yes but this is not my project. 😔

**Comment by RDiMag** [comment]
@zetabug Good morning! Can I claim this issue?
