### ISSUE TITLE
add a button that tracks the location of the user and dislpays data through API

### ISSUE THREAD

**Issue by zetabug** [zetabug/react-weather-application#2]

**Comment by AnthonyHad** [comment]
Hi! 
I might be interested in taking this issue as I am currently ramping up on React. 
I'd need more clarifications, by button you mean a button when clicked prompts the user to allow for location and then displays the weather based on his location?

**Comment by zetabug** [comment]
Yes you got it right. I'm assigning you.

**Comment by AnthonyHad** [comment]
Will attempt it, I think I understood this

**Comment by AnthonyHad** [comment]
Made changes and it should be working, however I cloned the repo, branched out and attempted to push code but it doesn't work as I don't have permissions. What is the best way to push code? @zetabug

**Comment by AnthonyHad** [comment]
Have some ideas as well about refactoring the code and maybe add some styling ! 
Let me know ^^ @zetabug

**Comment by zetabug** [comment]
@AnthonyHad I would suggest that you should fork my repository then make changes to it by cloning it ,make sure to create a new branch , then push the changes to that repo, then make a pull request,  I'll review the PR then accept it.

**Comment by AnthonyHad** [comment]
@zetabug Alright, will attempt this

**Comment by AnthonyHad** [comment]
@zetabug you can assign me and move to done ^^
